// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MIANwbLARFK0sb0Jc0jLl0Qmu_O-oCs',
    appId: '1:894674766656:web:44abce73ff29b4f4cfc8a5',
    messagingSenderId: '894674766656',
    projectId: 'comptrain-4ab99',
    authDomain: 'comptrain-4ab99.firebaseapp.com',
    storageBucket: 'comptrain-4ab99.firebasestorage.app',
    measurementId: 'G-6D810TWD70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6SyPs3JP98bw_QlSNBuuuSDS06wHWHc',
    appId: '1:894674766656:android:63995c55b2083440cfc8a5',
    messagingSenderId: '894674766656',
    projectId: 'comptrain-4ab99',
    storageBucket: 'comptrain-4ab99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIhGXFzRHVqbzlHqx9gYvN9r1Ads7sdQ',
    appId: '1:894674766656:ios:30ade933c842c87bcfc8a5',
    messagingSenderId: '894674766656',
    projectId: 'comptrain-4ab99',
    storageBucket: 'comptrain-4ab99.firebasestorage.app',
    iosBundleId: 'com.antivariantum.comptrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhWa1V3s6JO0PXftwZgaTaSVTaKbNTo0',
    appId: '1:894674766656:ios:dc15e376b7c6c5a7cfc8a5',
    messagingSenderId: '894674766656',
    projectId: 'comptrain-4ab99',
    storageBucket: 'comptrain-4ab99.firebasestorage.app',
    iosBundleId: 'com.antivariantum.comptrain.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6MIANwbLARFK0sb0Jc0jLl0Qmu_O-oCs',
    appId: '1:894674766656:web:e3fd6e6a9b1b2e99cfc8a5',
    messagingSenderId: '894674766656',
    projectId: 'comptrain-4ab99',
    authDomain: 'comptrain-4ab99.firebaseapp.com',
    storageBucket: 'comptrain-4ab99.firebasestorage.app',
    measurementId: 'G-ZPR3GZ6RJB',
  );

}